apiVersion: v1
kind: Service
metadata:
  name: degen-server-service
  labels:
    app: degen-server
spec:
  selector:
    app: degen-server
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
  sessionAffinity: ClientIP 