apiVersion: v1
kind: Pod
metadata:
  name: data-mover
spec:
  containers:
  - name: data-mover
    image: ubuntu:20.04
    command: ["sleep", "3600"]
    volumeMounts:
    - name: old-data
      mountPath: /old-data
    - name: new-data
      mountPath: /new-data
  volumes:
  - name: old-data
    persistentVolumeClaim:
      claimName: degen-server-db-pvc
  - name: new-data
    persistentVolumeClaim:
      claimName: degen-server-db-pvc-rwx 